### NumPy Indexing and Selection
In this lecture we will discuss how to select elements or groups of elements from an array.

In [1]:
import numpy as np

In [2]:
# creating sample array
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

### Bracket Indexing and Selection
The simplest way to pick one or some elements of an array looks very similar to python lists:

In [3]:
#Get a value at an index
arr[8]

8

In [4]:
# get an value from range
arr[4:7]

array([4, 5, 6])

In [5]:
#Get values in a range
arr[0:5]

array([0, 1, 2, 3, 4])

### Broadcasting
Numpy arrays differ from a normal Python list because of their ability to broadcast:

In [6]:
arr[4:8] = 10

#Show
arr

array([ 0,  1,  2,  3, 10, 10, 10, 10,  8,  9, 10])

In [10]:
# Reset array, we'll see why I had to reset in  a moment
arr  = np.arange(0,15)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [11]:
# important notes on slice
slice_arry = arr[0:6]
slice_arry

array([0, 1, 2, 3, 4, 5])

In [12]:
# change slice
slice_arry[:] = 20
slice_arry

array([20, 20, 20, 20, 20, 20])

Now note the changes also occur in our original array!

In [13]:
arr

array([20, 20, 20, 20, 20, 20,  6,  7,  8,  9, 10, 11, 12, 13, 14])

Data is not copied, it's a view of the original array! This avoids memory problems!

In [14]:
##To get a copy, need to be explicit
arr_copy = arr.copy()
arr_copy

array([20, 20, 20, 20, 20, 20,  6,  7,  8,  9, 10, 11, 12, 13, 14])

### Indexing a 2D array (matrices)
The general format is arr_2d[row][col] or arr_2d[row,col]. I recommend usually using the comma notation for clarity.

In [26]:
arr_2d = np.array(([1,3,33],[43,55,6],[75,23,19]))
arr_2d

array([[ 1,  3, 33],
       [43, 55,  6],
       [75, 23, 19]])

In [27]:
arr_2d[1]

array([43, 55,  6])

In [28]:
# Format is arr_2d[row][col] or arr_2d[row,col]

# Getting individual element value
arr_2d[1][0]

43

In [29]:
# Getting individual element value
arr_2d[1,0]

43

In [38]:
# 2D array slicing

#Shape (2,2) from top right corner
arr_2d[:2,:2]

array([[ 1,  3],
       [43, 55]])

In [40]:
#Shape bottom row
arr_2d[2]

array([75, 23, 19])

In [51]:
#Shape bottom row
arr_2d[2,:]

array([75, 23, 19])

### Fancy Indexing
Fancy indexing allows you to select entire rows or columns out of order,to show this, let's quickly build out a numpy array:

In [54]:
# Set up matrix
arr2d = np.zeros((10,10))
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [64]:
# Length of array
arr2dLnegth = arr2d.shape[1]
arr2dLnegth

10

In [65]:
# setup an array

for i in range(arr2dLnegth):
    arr2d[i] = i
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

Fancy indexing allows the following

In [68]:
arr2d[[2,4,5,6]]

array([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.]])

In [69]:
#Allows in any order
arr2d[[6,4,2,7]]

array([[6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.]])

### Selection
Let's briefly go over how to use brackets for selection based off of comparison operators.

In [71]:
arr =  np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [72]:
arr > 6

array([False, False, False, False, False, False, False,  True,  True,
        True])

In [73]:
bool_ar = arr > 4
bool_ar

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [75]:
arr[bool_ar]

array([5, 6, 7, 8, 9])

In [76]:
arr[arr > 3]

array([4, 5, 6, 7, 8, 9])

In [77]:
x = 2
arr[arr > x]

array([3, 4, 5, 6, 7, 8, 9])

## Great Job!