## Standarization: Z = ( X - (mean) ) / Standar Deviation

In [5]:
from sklearn.preprocessing import StandardScaler
import numpy as np

data = np.array([[0, 0], [1, 0], [0, 1], [1, 1]])
scaler = StandardScaler()
scaled_data = scaler.fit_transform(data)

print(data)

[[0 0]
 [1 0]
 [0 1]
 [1 1]]


In [7]:
print(scaled_data)

[[-1. -1.]
 [ 1. -1.]
 [-1.  1.]
 [ 1.  1.]]


In [3]:
data = np.array([[5, 4], [1, 4], [5, 1], [4, 1]])
scaler = StandardScaler()
scaled_data = scaler.fit_transform(data)

print(data)

[[5 4]
 [1 4]
 [5 1]
 [4 1]]


In [4]:
print(scaled_data)

[[ 0.76249285  1.        ]
 [-1.67748427  1.        ]
 [ 0.76249285 -1.        ]
 [ 0.15249857 -1.        ]]
