Numpy has many built-in functions and capabilities. We won't cover them all but instead we will focus on some of the most important aspects of Numpy: vectors,arrays,matrices, and number generation. Let's start by discussing arrays.

# Numpy Arrays

NumPy arrays are the main way we will use Numpy throughout the course. Numpy arrays essentially come in two flavors: vectors and matrices. Vectors are strictly 1-d arrays and matrices are 2-d (but you should note a matrix can still have only one row or one column).

Let's begin our introduction by exploring how to create NumPy arrays.

## Creating NumPy Arrays

### From a Python List

We can create an array by directly converting a list or list of lists:

In [121]:
import numpy as np

In [122]:
list = [1,2,3]
print(list)

[1, 2, 3]


In [123]:
np.array(list)

array([1, 2, 3])

In [124]:
matrix = [[1,2],[3,4],[5,6]]
matrix

[[1, 2], [3, 4], [5, 6]]

In [125]:
np.array(matrix)

array([[1, 2],
       [3, 4],
       [5, 6]])

# Built-in Methods

There are lots of built-in ways to generate Arrays

### arange

Return evenly spaced values within a given interval.

In [126]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [127]:
np.arange(0,20,3)

array([ 0,  3,  6,  9, 12, 15, 18])

## zeros and ones
## Generate arrays of zeros or ones

In [128]:
np.zeros(3)

array([0., 0., 0.])

In [129]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [130]:
np.ones(3)

array([1., 1., 1.])

In [131]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

#### linspace
#### Return evenly spaced numbers over a specified interval.

In [132]:
np.linspace(0,20,10)

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

### eye¶
### Creates an identity matrix

In [133]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### Random¶
Numpy also has lots of ways to create random number arrays:

###  rand
Create an array of the given shape and populate it with random samples from a uniform distribution over [0, 1).

In [134]:
np.random.rand(20)

array([0.0257213 , 0.51150996, 0.3928975 , 0.4017793 , 0.01506455,
       0.41264002, 0.52515519, 0.00649998, 0.5506596 , 0.32683003,
       0.39494617, 0.39690144, 0.16302138, 0.61142243, 0.27966775,
       0.61147323, 0.92610211, 0.96822815, 0.80333562, 0.16812198])

In [135]:
#  3X3 Matrix
np.random.rand(3,3)

array([[0.78217903, 0.72533481, 0.24525804],
       [0.85538803, 0.3242353 , 0.65908476],
       [0.70202197, 0.76804709, 0.88735283]])

### randint¶
<p> Return random integers from low (inclusive) to high (exclusive). </p>

In [136]:
np.random.randint(20)

19

In [137]:
np.random.randint(3, 10, 4)

array([7, 7, 9, 4])

## Reshape

Returns an array containing the same data with a new shape.

In [139]:
arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [140]:
resh = arr.reshape(5,5)
resh 

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [141]:
# Access Method od n d array 
resh[1][4]

9

#### max,min,argmax,argmin¶
These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax

In [94]:
# generate Random numbers 
random_int = np.random.randint(0,50,5)
print(random_int)
# Check max value
random_int.max()

[38 18 41 35  7]


41

In [95]:
random_int.min()

7

In [96]:
random_int.argmax()

2

In [97]:
random_int.argmin()

4

In [113]:
def check_random():
    # generate Random numbers 
    random_int = np.random.randint(0,50,5)
    print(random_int)
    # Check max value
    print('Min', random_int.min())
    print('Max' , random_int.max())
    print('argmin' , random_int.argmin())
    print('argmax' , random_int.argmax())

check_random()

[15 48 45  3 20]
Min 3
Max 48
argmin 3
argmax 1


### Shape
Shape is an attribute that arrays have (not a method):

In [114]:
# Vector
arr.shape

(25,)

In [115]:
# Notice the two sets of brackets
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [116]:
arr.reshape(1,25).shape

(1, 25)

In [117]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [118]:
arr.reshape(25,1).shape

(25, 1)

### dtype
You can also grab the data type of the object in the array:

In [119]:
arr.dtype

dtype('int32')

## Great Job!